# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0002_auto_20151217_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=75)),
                ('event_city', models.CharField(max_length=75)),
                ('event_state', models.CharField(max_length=75)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=11)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='smacker',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='smacker',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Smacker',
        ),
    ]
