# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0003_auto_20151217_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smackevent',
            old_name='event_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='smackevent',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='smackevent',
            old_name='event_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='smackpost',
            old_name='smack_text',
            new_name='post',
        ),
        migrations.AddField(
            model_name='smackpost',
            name='event',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='smack.SmackEvent'),
            preserve_default=False,
        ),
    ]
