# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0004_auto_20151217_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='smackpost',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smackpost',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=11),
            preserve_default=False,
        ),
    ]
