# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smack', '0005_auto_20151218_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('University of Kentucky', 'University of Kentucky'), ('Duke University', 'Duke University'), ('University of North Carolina', 'University of North Carolina'), ('Wisconsin', 'Wisconsin'), ('Other', 'Other')], default='Other', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
