# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smack', '0008_auto_20160317_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='smackpost',
            name='downs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smackpost',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smackpost',
            name='ups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='smack_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smack.SmackPost'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
