# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0011_vote'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smackpost',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='smackpost',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
