# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0013_auto_20160322_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AlterModelOptions(
            name='smackpost',
            options={'ordering': ['-vote_count']},
        ),
        migrations.RemoveField(
            model_name='smackpost',
            name='votes',
        ),
        migrations.AddField(
            model_name='smackpost',
            name='voting_users',
            field=models.ManyToManyField(to='smack.Smacker'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
