# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0014_auto_20160324_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smackpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='smackpost',
            name='vote_count',
        ),
        migrations.AlterOrderWithRespectTo(
            name='smackpost',
            order_with_respect_to='voting_users',
        ),
    ]
