# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0015_auto_20160325_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='smackpost',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
