# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0016_smackpost_vote_count'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='smackpost',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='smackpost',
            name='vote_count',
        ),
    ]
